# Data Cleaning Report

### CGPA Cleaning

- Valid CGPA range: 0–10.
- 7 records contained invalid CGPA values greater than 10.
- No values were below 0.
- Invalid values (11 and 12) were converted to NaN because the correct CGPA could not be determined.
- The original student records were retained.
- Missing CGPA values will be handled separately during the missing-value treatment phase.

In [2]:
import pandas as pd
import numpy as np
df = pd.read_csv('student_placement_messy.csv')

## Categorical Cleaning

#### Branch Column Cleaning

In [3]:
df['Branch'].value_counts(dropna=False)

Branch
CSE            516
ECE            352
IT             337
Mechanical     257
Civil          256
NaN             27
cse             12
 ECE            11
ece              9
 IT              8
IT               7
CSE              7
 Civil           6
it               6
mechanical       6
civil            6
 CSE             6
CIVIL            6
ECE              5
 MECHANICAL      3
Mechanical       2
Name: count, dtype: int64

In [4]:
df['Branch'] = df['Branch'].str.strip()

In [5]:
df['Branch'] = df['Branch'].str.upper()

In [6]:
df['Branch'].unique()

<ArrowStringArray>
['CIVIL', 'CSE', 'ECE', 'IT', 'MECHANICAL', nan]
Length: 6, dtype: str

In [7]:
branch_map = {
    'CIVIL':'Civil', 
    'CSE':'CSE', 
    'ECE':'ECE', 
    'IT':'IT', 
    'MECHANICAL':'Mechanical'
}

df['Branch'] = df['Branch'].map(branch_map)

In [8]:
df['Branch'].value_counts(dropna=False)

Branch
CSE           541
ECE           377
IT            358
Civil         274
Mechanical    268
NaN            27
Name: count, dtype: int64

#### Internship Column Cleaning

In [9]:
df['Internship'].value_counts(dropna=False)

Internship
No       966
Yes      770
NaN       28
 yes      26
No        16
YES       16
yes       12
NO        11
Name: count, dtype: int64

In [10]:
df['Internship'] = df['Internship'].str.strip()

In [11]:
df['Internship'] = df['Internship'].str.capitalize()

In [12]:
df['Internship'].value_counts(dropna=False)

Internship
No     993
Yes    824
NaN     28
Name: count, dtype: int64

#### Gender Column Cleaning

In [13]:
df['Gender'].value_counts(dropna=False)

Gender
Male      871
Female    844
male       46
female     46
NaN        38
Name: count, dtype: int64

In [14]:
df['Gender'] = df['Gender'].str.strip()

In [15]:
df['Gender'] = df['Gender'].str.capitalize()

In [16]:
df['Gender'].value_counts(dropna = False)

Gender
Male      917
Female    890
NaN        38
Name: count, dtype: int64

#### Placement_Status Column Checking

In [17]:
df['Placement_Status'].value_counts(dropna=False)

Placement_Status
Placed        1304
Not Placed     452
NOT PLACED      18
Not placed      17
NaN             16
not placed      16
 placed         10
PLACED           6
placed           6
Name: count, dtype: int64

In [18]:
df['Placement_Status'] = df['Placement_Status'].str.strip()

In [19]:
df['Placement_Status'] = df['Placement_Status'].str.capitalize()

In [20]:
df['Placement_Status'].value_counts(dropna = False)

Placement_Status
Placed        1326
Not placed     503
NaN             16
Name: count, dtype: int64

#### Final Check

In [21]:
final_check = ['Gender','Internship','Branch','Placement_Status']
for col in final_check:
    print(df[col].value_counts(dropna=False))

Gender
Male      917
Female    890
NaN        38
Name: count, dtype: int64
Internship
No     993
Yes    824
NaN     28
Name: count, dtype: int64
Branch
CSE           541
ECE           377
IT            358
Civil         274
Mechanical    268
NaN            27
Name: count, dtype: int64
Placement_Status
Placed        1326
Not placed     503
NaN             16
Name: count, dtype: int64

## Numeric Cleaning

#### CGPA Column Cleaning

In [22]:
df['CGPA'].describe()

count    1807.000000
mean        7.501350
std         1.049165
min         0.000000
25%         6.790000
50%         7.500000
75%         8.170000
max        12.000000
Name: CGPA, dtype: float64

In [23]:
df[df['CGPA']>10]

,Student_ID,Name,Gender,Branch,CGPA,10th_Percentage,12th_Percentage,Attendance,Backlogs,Internship,Projects,Certifications,Programming_Skill,Communication_Skill,Aptitude_Score,Placement_Status,Package_LPA,Graduation_Year,Application_Date
80,ST0212,Student_0212,Male,CSE,11.0,91.38,81.49,78.59,0,No,3.0,6,5.0,1.0,83.96,Not placed,0.0,2026,2023-06-06
155,ST0672,Student_0672,Female,CSE,12.0,84.37,64.05,NaN,0,Yes,2.0,0,3.0,5.0,54.04,Not placed,0.0,2023,2024-05-14
611,ST0218,Student_0218,Male,Civil,12.0,74.05,85.83,82.93,0,No,4.0,0,5.0,4.0,64.64,Placed,7.97,2026,2023-06-11
827,ST0045,Student_0045,Female,CSE,12.0,78.56,76.39,72.65,0,Yes,4.0,6,8.0,10.0,59.78,Not placed,₹0.0,2026,2023-02-02
1302,ST0281,Student_0281,Female,Civil,12.0,72.44,72.35,85.77,4,No,2.0,6,3.0,5.0,59.77,Placed,12.78,2024,2023-07-28
1426,ST0013,Student_0013,Male,ECE,11.0,69.03,73.22,87.95,0,No,2.0,1,2.0,5.0,81.02,Placed,9.34,2025,2023-01-09
1544,ST0218,Student_0218,Male,Civil,12.0,74.05,85.83,83.93,0,No,4.0,0,5.0,4.0,64.64,Placed,7.97,2026,2023-06-11

In [24]:
df.loc[df['CGPA']>10,'CGPA'] = np.nan

In [25]:
df['CGPA'].max()

np.float64(10.0)

In [26]:
df['CGPA'].isna().sum()

np.int64(45)

#### Attendance Column Cleaning

In [27]:
df['Attendance'].describe()

count      1790
unique     1376
top       100.0
freq         44
Name: Attendance, dtype: object

In [28]:
df['Attendance'].map(type).value_counts(dropna = False)

Attendance
<class 'str'>      1790
<class 'float'>      55
Name: count, dtype: int64

In [44]:
df['Attendance'] = df['Attendance'].astype(str).str.replace('%','',regex=False)

In [45]:
df['Attendance']

0       81.18
1       89.46
2       56.04
3       79.67
4        87.8
        ...
1840    73.63
1841    99.13
1842    80.66
1843    70.12
1844    73.62
Name: Attendance, Length: 1845, dtype: str

In [46]:
df['Attendance'] = pd.to_numeric(df['Attendance'],errors='coerce')

In [47]:
df['Attendance']

0       81.18
1       89.46
2       56.04
3       79.67
4       87.80
        ...
1840    73.63
1841    99.13
1842    80.66
1843    70.12
1844    73.62
Name: Attendance, Length: 1845, dtype: float64

In [42]:
df["Attendance"].map(type).value_counts()

Attendance
<class 'float'>    1845
Name: count, dtype: int64

In [52]:
df[df['Attendance']<0]

Empty DataFrame
Columns: [Student_ID, Name, Gender, Branch, CGPA, 10th_Percentage, 12th_Percentage, Attendance, Backlogs, Internship, Projects, Certifications, Programming_Skill, Communication_Skill, Aptitude_Score, Placement_Status, Package_LPA, Graduation_Year, Application_Date]
Index: []

In [51]:
df[df['Attendance']>100]

,Student_ID,Name,Gender,Branch,CGPA,10th_Percentage,12th_Percentage,Attendance,Backlogs,Internship,Projects,Certifications,Programming_Skill,Communication_Skill,Aptitude_Score,Placement_Status,Package_LPA,Graduation_Year,Application_Date
980,ST0152,Student_0152,Male,ECE,6.82,68.02,88.32,145.0,1,No,1.0,2,7.0,2.0,54.73,Not placed,0.0,2023,2023-04-23
1126,ST0264,Student_0264,Male,Mechanical,6.85,50.74,78.71,145.0,0,No,4.0,0,9.0,1.0,65.79,Placed,12.34,2026,2023-07-15
1150,ST0483,Student_0483,Male,Civil,7.30,64.42,67.76,145.0,3,No,1.0,0,3.0,8.0,NaN,Placed,10.24,2025,2023-12-25
1258,ST0932,Student_0932,Female,ECE,7.17,66.74,66.07,145.0,0,No,5.0,2,2.0,6.0,79.09,Not placed,11.02,2026,2024-11-23
1364,ST1269,Student_1269,Male,ECE,9.77,66.54,72.94,145.0,0,No,4.0,0,5.0,1.0,59.60,Placed,13.73,2024,2025-08-01
1378,ST1557,Student_1557,Female,IT,9.99,76.34,84.83,101.0,1,No,1.0,4,10.0,8.0,63.92,Placed,14.56,2026,2026-03-03
1479,ST1197,Student_1197,Female,ECE,7.50,72.26,73.23,101.0,0,Yes,0.0,3,7.0,10.0,70.66,Placed,9.83,2023,2025-06-08

In [55]:
df.loc[df['Attendance']>100 , "Attendance"] = np.nan

In [56]:
df['Attendance'].describe

<bound method NDFrame.describe of 0       81.18
1       89.46
2       56.04
3       79.67
4       87.80
        ...
1840    73.63
1841    99.13
1842    80.66
1843    70.12
1844    73.62
Name: Attendance, Length: 1845, dtype: float64>

In [57]:
df['Attendance'].isna().sum()

np.int64(62)

#### 10th_Percentage Column Cleaning