# Data Cleaning

## Categorical Cleaning

Standardized:
- Branch
- Internship
- Placement_Status
- Gender

Operations:
- Removed leading/trailing spaces
- Standardized capitalization
- Standardized category labels
- Missing categorical values were represented as `Unknown`

## Numeric Cleaning

Validated:
- CGPA: 0–10
- Attendance: 0–100
- 10th Percentage: 0–100
- 12th Percentage: 0–100

Invalid values were identified and converted to missing values where the correct original value could not be determined.

Remaining unknown numeric values were retained as `NaN`.

## Date Cleaning

- Converted `Application_Date` to datetime format.
- Invalid/unavailable dates were retained as `NaT`.

## Duplicate Handling

- Duplicate records were identified and removed.
- Duplicate count was verified after removal.

## Missing Value Policy

Missing values were not blindly replaced.

- Categorical unknowns → `Unknown`
- Numeric unknowns → `NaN`
- Date unknowns → `NaT`

This preserves uncertainty instead of inventing values.

In [1]:
import pandas as pd
import numpy as np
df = pd.read_csv('student_placement_messy.csv')

## Categorical Cleaning

#### Branch Column Cleaning

In [2]:
df['Branch'].value_counts(dropna=False)

Branch
CSE            516
ECE            352
IT             337
Mechanical     257
Civil          256
NaN             27
cse             12
 ECE            11
ece              9
 IT              8
IT               7
CSE              7
 Civil           6
it               6
mechanical       6
civil            6
 CSE             6
CIVIL            6
ECE              5
 MECHANICAL      3
Mechanical       2
Name: count, dtype: int64

In [3]:
df['Branch'] = df['Branch'].str.strip()

In [4]:
df['Branch'] = df['Branch'].str.upper()

In [5]:
df['Branch'].unique()

<ArrowStringArray>
['CIVIL', 'CSE', 'ECE', 'IT', 'MECHANICAL', nan]
Length: 6, dtype: str

In [6]:
branch_map = {
    'CIVIL':'Civil', 
    'CSE':'CSE', 
    'ECE':'ECE', 
    'IT':'IT', 
    'MECHANICAL':'Mechanical'
}

df['Branch'] = df['Branch'].map(branch_map)

In [7]:
df['Branch'].value_counts(dropna=False)

Branch
CSE           541
ECE           377
IT            358
Civil         274
Mechanical    268
NaN            27
Name: count, dtype: int64

#### Internship Column Cleaning

In [8]:
df['Internship'].value_counts(dropna=False)

Internship
No       966
Yes      770
NaN       28
 yes      26
No        16
YES       16
yes       12
NO        11
Name: count, dtype: int64

In [9]:
df['Internship'] = df['Internship'].str.strip()

In [10]:
df['Internship'] = df['Internship'].str.capitalize()

In [11]:
df['Internship'].value_counts(dropna=False)

Internship
No     993
Yes    824
NaN     28
Name: count, dtype: int64

#### Gender Column Cleaning

In [12]:
df['Gender'].value_counts(dropna=False)

Gender
Male      871
Female    844
male       46
female     46
NaN        38
Name: count, dtype: int64

In [13]:
df['Gender'] = df['Gender'].str.strip()

In [14]:
df['Gender'] = df['Gender'].str.capitalize()

In [15]:
df['Gender'].value_counts(dropna = False)

Gender
Male      917
Female    890
NaN        38
Name: count, dtype: int64

#### Placement_Status Column Checking

In [16]:
df['Placement_Status'].value_counts(dropna=False)

Placement_Status
Placed        1304
Not Placed     452
NOT PLACED      18
Not placed      17
NaN             16
not placed      16
 placed         10
PLACED           6
placed           6
Name: count, dtype: int64

In [17]:
df['Placement_Status'] = df['Placement_Status'].str.strip()

In [18]:
df['Placement_Status'] = df['Placement_Status'].str.capitalize()

In [19]:
df['Placement_Status'].value_counts(dropna = False)

Placement_Status
Placed        1326
Not placed     503
NaN             16
Name: count, dtype: int64

#### Final Check

In [20]:
final_check = ['Gender','Internship','Branch','Placement_Status']
for col in final_check:
    print(df[col].value_counts(dropna=False))

Gender
Male      917
Female    890
NaN        38
Name: count, dtype: int64
Internship
No     993
Yes    824
NaN     28
Name: count, dtype: int64
Branch
CSE           541
ECE           377
IT            358
Civil         274
Mechanical    268
NaN            27
Name: count, dtype: int64
Placement_Status
Placed        1326
Not placed     503
NaN             16
Name: count, dtype: int64

## Numeric Cleaning

#### CGPA Column Cleaning

In [21]:
df['CGPA'].describe()

count    1807.000000
mean        7.501350
std         1.049165
min         0.000000
25%         6.790000
50%         7.500000
75%         8.170000
max        12.000000
Name: CGPA, dtype: float64

In [22]:
df[df['CGPA']>10]

,Student_ID,Name,Gender,Branch,CGPA,10th_Percentage,12th_Percentage,Attendance,Backlogs,Internship,Projects,Certifications,Programming_Skill,Communication_Skill,Aptitude_Score,Placement_Status,Package_LPA,Graduation_Year,Application_Date
80,ST0212,Student_0212,Male,CSE,11.0,91.38,81.49,78.59,0,No,3.0,6,5.0,1.0,83.96,Not placed,0.0,2026,2023-06-06
155,ST0672,Student_0672,Female,CSE,12.0,84.37,64.05,NaN,0,Yes,2.0,0,3.0,5.0,54.04,Not placed,0.0,2023,2024-05-14
611,ST0218,Student_0218,Male,Civil,12.0,74.05,85.83,82.93,0,No,4.0,0,5.0,4.0,64.64,Placed,7.97,2026,2023-06-11
827,ST0045,Student_0045,Female,CSE,12.0,78.56,76.39,72.65,0,Yes,4.0,6,8.0,10.0,59.78,Not placed,₹0.0,2026,2023-02-02
1302,ST0281,Student_0281,Female,Civil,12.0,72.44,72.35,85.77,4,No,2.0,6,3.0,5.0,59.77,Placed,12.78,2024,2023-07-28
1426,ST0013,Student_0013,Male,ECE,11.0,69.03,73.22,87.95,0,No,2.0,1,2.0,5.0,81.02,Placed,9.34,2025,2023-01-09
1544,ST0218,Student_0218,Male,Civil,12.0,74.05,85.83,83.93,0,No,4.0,0,5.0,4.0,64.64,Placed,7.97,2026,2023-06-11

In [23]:
df.loc[df['CGPA']>10,'CGPA'] = np.nan

In [24]:
df['CGPA'].max()

np.float64(10.0)

In [25]:
df['CGPA'].isna().sum()

np.int64(45)

#### Attendance Column Cleaning

In [26]:
df['Attendance'].describe()

count      1790
unique     1376
top       100.0
freq         44
Name: Attendance, dtype: object

In [27]:
df['Attendance'].map(type).value_counts(dropna = False)

Attendance
<class 'str'>      1790
<class 'float'>      55
Name: count, dtype: int64

In [28]:
df['Attendance'] = df['Attendance'].astype(str).str.replace('%','',regex=False)

In [29]:
df['Attendance']

0       81.18
1       89.46
2       56.04
3       79.67
4        87.8
        ...
1840    73.63
1841    99.13
1842    80.66
1843    70.12
1844    73.62
Name: Attendance, Length: 1845, dtype: str

In [30]:
df['Attendance'] = pd.to_numeric(df['Attendance'],errors='coerce')

In [31]:
df['Attendance']

0       81.18
1       89.46
2       56.04
3       79.67
4       87.80
        ...
1840    73.63
1841    99.13
1842    80.66
1843    70.12
1844    73.62
Name: Attendance, Length: 1845, dtype: float64

In [32]:
df["Attendance"].map(type).value_counts()

Attendance
<class 'float'>    1845
Name: count, dtype: int64

In [33]:
df[df['Attendance']<0]

Empty DataFrame
Columns: [Student_ID, Name, Gender, Branch, CGPA, 10th_Percentage, 12th_Percentage, Attendance, Backlogs, Internship, Projects, Certifications, Programming_Skill, Communication_Skill, Aptitude_Score, Placement_Status, Package_LPA, Graduation_Year, Application_Date]
Index: []

In [34]:
df[df['Attendance']>100]

,Student_ID,Name,Gender,Branch,CGPA,10th_Percentage,12th_Percentage,Attendance,Backlogs,Internship,Projects,Certifications,Programming_Skill,Communication_Skill,Aptitude_Score,Placement_Status,Package_LPA,Graduation_Year,Application_Date
980,ST0152,Student_0152,Male,ECE,6.82,68.02,88.32,145.0,1,No,1.0,2,7.0,2.0,54.73,Not placed,0.0,2023,2023-04-23
1126,ST0264,Student_0264,Male,Mechanical,6.85,50.74,78.71,145.0,0,No,4.0,0,9.0,1.0,65.79,Placed,12.34,2026,2023-07-15
1150,ST0483,Student_0483,Male,Civil,7.30,64.42,67.76,145.0,3,No,1.0,0,3.0,8.0,NaN,Placed,10.24,2025,2023-12-25
1258,ST0932,Student_0932,Female,ECE,7.17,66.74,66.07,145.0,0,No,5.0,2,2.0,6.0,79.09,Not placed,11.02,2026,2024-11-23
1364,ST1269,Student_1269,Male,ECE,9.77,66.54,72.94,145.0,0,No,4.0,0,5.0,1.0,59.60,Placed,13.73,2024,2025-08-01
1378,ST1557,Student_1557,Female,IT,9.99,76.34,84.83,101.0,1,No,1.0,4,10.0,8.0,63.92,Placed,14.56,2026,2026-03-03
1479,ST1197,Student_1197,Female,ECE,7.50,72.26,73.23,101.0,0,Yes,0.0,3,7.0,10.0,70.66,Placed,9.83,2023,2025-06-08

In [35]:
df.loc[df['Attendance']>100 , "Attendance"] = np.nan

In [36]:
df['Attendance'].describe

<bound method NDFrame.describe of 0       81.18
1       89.46
2       56.04
3       79.67
4       87.80
        ...
1840    73.63
1841    99.13
1842    80.66
1843    70.12
1844    73.62
Name: Attendance, Length: 1845, dtype: float64>

In [37]:
df['Attendance'].isna().sum()

np.int64(62)

#### 10th_Percentage Column Cleaning

In [38]:
df['10th_Percentage'].map(type).value_counts(dropna=False)

10th_Percentage
<class 'float'>    1845
Name: count, dtype: int64

In [39]:
df[df['10th_Percentage']<0]

Empty DataFrame
Columns: [Student_ID, Name, Gender, Branch, CGPA, 10th_Percentage, 12th_Percentage, Attendance, Backlogs, Internship, Projects, Certifications, Programming_Skill, Communication_Skill, Aptitude_Score, Placement_Status, Package_LPA, Graduation_Year, Application_Date]
Index: []

In [40]:
df[df['10th_Percentage']>100]

,Student_ID,Name,Gender,Branch,CGPA,10th_Percentage,12th_Percentage,Attendance,Backlogs,Internship,Projects,Certifications,Programming_Skill,Communication_Skill,Aptitude_Score,Placement_Status,Package_LPA,Graduation_Year,Application_Date
103,ST1789,Student_1789,Male,IT,8.45,105.0,46.83,75.36,0,No,4.0,2,7.0,9.0,76.91,Placed,12.88,2025,2026-08-22
672,ST1635,Student_1635,Male,Mechanical,7.73,105.0,84.42,89.39,0,No,3.0,4,8.0,1.0,67.63,Placed,11.97,2023,2026-04-30
1272,ST1677,Student_1677,Male,Civil,7.53,105.0,68.87,90.53,0,No,2.0,1,2.0,5.0,77.22,Not placed,0.0,2024,31/05/2026
1471,ST0895,Student_0895,Female,CSE,5.63,150.0,65.80,86.13,0,No,2.0,3,2.0,5.0,86.03,Placed,8.51,2025,2024-10-26
1738,ST0734,Student_0734,Female,Mechanical,8.18,105.0,79.59,79.14,0,Yes,2.0,3,2.0,2.0,66.25,Placed,12.41,2024,2024-06-29

In [41]:
df.loc[df['10th_Percentage']>100, '10th_Percentage'] = np.nan

In [42]:
df['10th_Percentage'].describe()

count    1840.000000
mean       74.636185
std         9.998373
min         5.000000
25%        68.330000
50%        74.845000
75%        81.452500
max       100.000000
Name: 10th_Percentage, dtype: float64

In [43]:
df['10th_Percentage'].isna().sum()

np.int64(5)

#### 12th_Percentage Column Cleaning

In [44]:
df['12th_Percentage'].describe()

count    1845.000000
mean       72.597252
std        11.943272
min        10.000000
25%        64.620000
50%        72.560000
75%        80.560000
max       130.000000
Name: 12th_Percentage, dtype: float64

In [45]:
df['12th_Percentage'].map(type).value_counts(dropna=False)

12th_Percentage
<class 'float'>    1845
Name: count, dtype: int64

In [46]:
df[df['12th_Percentage']<0]

Empty DataFrame
Columns: [Student_ID, Name, Gender, Branch, CGPA, 10th_Percentage, 12th_Percentage, Attendance, Backlogs, Internship, Projects, Certifications, Programming_Skill, Communication_Skill, Aptitude_Score, Placement_Status, Package_LPA, Graduation_Year, Application_Date]
Index: []

In [47]:
df[df['12th_Percentage']>100]

,Student_ID,Name,Gender,Branch,CGPA,10th_Percentage,12th_Percentage,Attendance,Backlogs,Internship,Projects,Certifications,Programming_Skill,Communication_Skill,Aptitude_Score,Placement_Status,Package_LPA,Graduation_Year,Application_Date
27,ST0785,Student_0785,Female,CSE,8.19,75.81,130.0,88.64,1,Yes,5.0,2,3.0,7.0,57.20,Placed,₹9.82,2023,08-06-2024
385,ST0931,Student_0931,Male,Civil,7.82,70.24,130.0,72.50,0,No,0.0,0,8.0,5.0,67.83,Placed,9.12,2026,2024-11-22
896,ST0184,Student_0184,Male,Civil,8.00,59.70,130.0,83.33,3,Yes,1.0,6,8.0,5.0,56.66,Placed,11.83,2024,2023-05-17

In [48]:
df.loc[df['12th_Percentage']>100,'12th_Percentage'] = np.nan

In [49]:
df[df['12th_Percentage']>100]

Empty DataFrame
Columns: [Student_ID, Name, Gender, Branch, CGPA, 10th_Percentage, 12th_Percentage, Attendance, Backlogs, Internship, Projects, Certifications, Programming_Skill, Communication_Skill, Aptitude_Score, Placement_Status, Package_LPA, Graduation_Year, Application_Date]
Index: []

In [50]:
df['12th_Percentage'].isna().sum()

np.int64(3)

## Date Issues

In [51]:
df['Application_Date'].dtype

In [52]:
df["Application_Date"].sample(30, random_state=42)

1572    2025-01-30
1160    2024-05-18
799            NaN
1531    2024-10-22
1323    2025-07-06
361     08-24-2025
239     2023-05-02
582     2026-02-10
1440    2024-06-05
1283    2026-01-14
1613    2025-09-08
607     2023-07-09
1284    2025-02-21
1087    2026-06-22
584     2024-06-06
1822    2024-11-12
1488    2025-10-15
1301    2024-04-16
1791    2025-07-11
1835    2025-12-21
1036    2025-06-20
700     2024-02-22
1561    2025-11-20
382     2025-12-06
1833    2023-01-21
1242    2024-08-01
351     2025-11-28
303     2025-12-25
764     2026-06-02
1360    2025-07-29
Name: Application_Date, dtype: str

In [53]:
df["Application_Date"].isna().sum()

np.int64(15)

In [54]:
df["Application_Date"] = pd.to_datetime(df["Application_Date"],errors="coerce")

In [55]:
df['Application_Date']

0      2023-06-01
1      2024-01-17
2      2024-02-28
3      2024-10-27
4      2025-04-15
          ...
1840   2023-02-27
1841   2024-12-09
1842   2024-08-13
1843   2025-11-17
1844   2023-07-11
Name: Application_Date, Length: 1845, dtype: datetime64[us]

In [56]:
df["Application_Date"].isna().sum()

np.int64(82)

## Duplicates Remove

In [57]:
df

,Student_ID,Name,Gender,Branch,CGPA,10th_Percentage,12th_Percentage,Attendance,Backlogs,Internship,Projects,Certifications,Programming_Skill,Communication_Skill,Aptitude_Score,Placement_Status,Package_LPA,Graduation_Year,Application_Date
0,ST0205,Student_0205,Female,Civil,8.39,73.89,91.41,81.18,1,No,3.0,6,8.0,8.0,70.32,Placed,12.33,2024,2023-06-01
1,ST0514,Student_0514,Female,CSE,6.85,81.80,83.22,89.46,0,Yes,0.0,5,4.0,10.0,65.44,Placed,8.07,2023,2024-01-17
2,ST0571,Student_0571,Female,ECE,7.89,65.41,70.56,56.04,1,No,5.0,1,2.0,1.0,51.71,Not placed,NaN,2024,2024-02-28
3,ST0896,Student_0896,Female,CSE,7.11,77.41,50.46,79.67,1,No,4.0,3,7.0,10.0,71.42,Not placed,0.0,2026,2024-10-27
4,ST1125,Student_1125,Female,IT,7.87,62.83,73.25,87.80,0,No,5.0,0,8.0,9.0,77.80,Not placed,0.0,2023,2025-04-15
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1840,ST0078,Student_0078,Female,CSE,7.86,68.70,69.03,73.63,0,Yes,4.0,6,8.0,2.0,58.84,Not placed,0.0,2023,2023-02-27
1841,ST0953,Student_0953,Male,Civil,5.53,66.48,80.87,99.13,0,Yes,1.0,0,10.0,6.0,55.79,Placed,10.84,2023,2024-12-09
1842,ST0795,Student_0795,Male,IT,7.59,74.19,85.32,80.66,0,No,1.0,4,4.0,4.0,77.74,Placed,11.54,2023,2024-08-13
1843,ST1415,Student_1415,Female,Civil,8.88,71.71,76.41,70.12,0,Yes,3.0,6,3.0,7.0,51.40,Placed,12.01,2025,2025-11-17
1844,ST0258,Student_0258,Female,Civil,6.58,67.84,73.45,73.62,1,No,2.0,1,2.0,3.0,67.15,Placed,10.79,2023,2023-07-11

In [58]:
df.duplicated().sum()

np.int64(25)

In [59]:
df = df.drop_duplicates()

In [60]:
df

,Student_ID,Name,Gender,Branch,CGPA,10th_Percentage,12th_Percentage,Attendance,Backlogs,Internship,Projects,Certifications,Programming_Skill,Communication_Skill,Aptitude_Score,Placement_Status,Package_LPA,Graduation_Year,Application_Date
0,ST0205,Student_0205,Female,Civil,8.39,73.89,91.41,81.18,1,No,3.0,6,8.0,8.0,70.32,Placed,12.33,2024,2023-06-01
1,ST0514,Student_0514,Female,CSE,6.85,81.80,83.22,89.46,0,Yes,0.0,5,4.0,10.0,65.44,Placed,8.07,2023,2024-01-17
2,ST0571,Student_0571,Female,ECE,7.89,65.41,70.56,56.04,1,No,5.0,1,2.0,1.0,51.71,Not placed,NaN,2024,2024-02-28
3,ST0896,Student_0896,Female,CSE,7.11,77.41,50.46,79.67,1,No,4.0,3,7.0,10.0,71.42,Not placed,0.0,2026,2024-10-27
4,ST1125,Student_1125,Female,IT,7.87,62.83,73.25,87.80,0,No,5.0,0,8.0,9.0,77.80,Not placed,0.0,2023,2025-04-15
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1840,ST0078,Student_0078,Female,CSE,7.86,68.70,69.03,73.63,0,Yes,4.0,6,8.0,2.0,58.84,Not placed,0.0,2023,2023-02-27
1841,ST0953,Student_0953,Male,Civil,5.53,66.48,80.87,99.13,0,Yes,1.0,0,10.0,6.0,55.79,Placed,10.84,2023,2024-12-09
1842,ST0795,Student_0795,Male,IT,7.59,74.19,85.32,80.66,0,No,1.0,4,4.0,4.0,77.74,Placed,11.54,2023,2024-08-13
1843,ST1415,Student_1415,Female,Civil,8.88,71.71,76.41,70.12,0,Yes,3.0,6,3.0,7.0,51.40,Placed,12.01,2025,2025-11-17
1844,ST0258,Student_0258,Female,Civil,6.58,67.84,73.45,73.62,1,No,2.0,1,2.0,3.0,67.15,Placed,10.79,2023,2023-07-11

In [61]:
df.reset_index(drop=True,inplace=True)

In [62]:
df

,Student_ID,Name,Gender,Branch,CGPA,10th_Percentage,12th_Percentage,Attendance,Backlogs,Internship,Projects,Certifications,Programming_Skill,Communication_Skill,Aptitude_Score,Placement_Status,Package_LPA,Graduation_Year,Application_Date
0,ST0205,Student_0205,Female,Civil,8.39,73.89,91.41,81.18,1,No,3.0,6,8.0,8.0,70.32,Placed,12.33,2024,2023-06-01
1,ST0514,Student_0514,Female,CSE,6.85,81.80,83.22,89.46,0,Yes,0.0,5,4.0,10.0,65.44,Placed,8.07,2023,2024-01-17
2,ST0571,Student_0571,Female,ECE,7.89,65.41,70.56,56.04,1,No,5.0,1,2.0,1.0,51.71,Not placed,NaN,2024,2024-02-28
3,ST0896,Student_0896,Female,CSE,7.11,77.41,50.46,79.67,1,No,4.0,3,7.0,10.0,71.42,Not placed,0.0,2026,2024-10-27
4,ST1125,Student_1125,Female,IT,7.87,62.83,73.25,87.80,0,No,5.0,0,8.0,9.0,77.80,Not placed,0.0,2023,2025-04-15
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1815,ST0078,Student_0078,Female,CSE,7.86,68.70,69.03,73.63,0,Yes,4.0,6,8.0,2.0,58.84,Not placed,0.0,2023,2023-02-27
1816,ST0953,Student_0953,Male,Civil,5.53,66.48,80.87,99.13,0,Yes,1.0,0,10.0,6.0,55.79,Placed,10.84,2023,2024-12-09
1817,ST0795,Student_0795,Male,IT,7.59,74.19,85.32,80.66,0,No,1.0,4,4.0,4.0,77.74,Placed,11.54,2023,2024-08-13
1818,ST1415,Student_1415,Female,Civil,8.88,71.71,76.41,70.12,0,Yes,3.0,6,3.0,7.0,51.40,Placed,12.01,2025,2025-11-17
1819,ST0258,Student_0258,Female,Civil,6.58,67.84,73.45,73.62,1,No,2.0,1,2.0,3.0,67.15,Placed,10.79,2023,2023-07-11

## Missing Values

In [63]:
missing = df.isnull().sum()
missing_percentage = (df.isnull().sum() / len(df) * 100).round(2)

missing_report = pd.DataFrame({
    "Missing_Count": missing,
    "Missing_Percentage": missing_percentage
})

missing_report[missing_report["Missing_Count"] > 0]

                     Missing_Count  Missing_Percentage
Gender                          37                2.03
Branch                          27                1.48
CGPA                            45                2.47
10th_Percentage                  5                0.27
12th_Percentage                  3                0.16
Attendance                      62                3.41
Internship                      28                1.54
Projects                        26                1.43
Programming_Skill               30                1.65
Communication_Skill             30                1.65
Aptitude_Score                  45                2.47
Placement_Status                16                0.88
Package_LPA                     31                1.70
Application_Date                82                4.51

#### Categorial Cleaning NaN

In [64]:
df['Gender'] = df['Gender'].fillna('Unknown')

In [65]:
df['Branch'] =df['Branch'].fillna('Unknown')

In [66]:
df['Internship'] = df['Internship'].fillna('Unknown')

In [67]:
df['Placement_Status'] = df['Placement_Status'].fillna('Unknown')

## Project Column Cleaning

In [80]:
df[df['Projects']<0]

Empty DataFrame
Columns: [Student_ID, Name, Gender, Branch, CGPA, 10th_Percentage, 12th_Percentage, Attendance, Backlogs, Internship, Projects, Certifications, Programming_Skill, Communication_Skill, Aptitude_Score, Placement_Status, Package_LPA, Graduation_Year, Application_Date]
Index: []

In [81]:
df.loc[df['Projects']<0, 'Projects'] = np.nan

In [82]:
df[df['Projects']<0]

Empty DataFrame
Columns: [Student_ID, Name, Gender, Branch, CGPA, 10th_Percentage, 12th_Percentage, Attendance, Backlogs, Internship, Projects, Certifications, Programming_Skill, Communication_Skill, Aptitude_Score, Placement_Status, Package_LPA, Graduation_Year, Application_Date]
Index: []

## Data Quality Cheching

In [83]:
print("Shape:", df.shape)

print("\nMissing values:")
print(df.isnull().sum()[df.isnull().sum() > 0])

print("\nDuplicate rows:")
print(df.duplicated().sum())

print("\nData types:")
print(df.dtypes)

Shape: (1820, 19)

Missing values:
CGPA                   45
10th_Percentage         5
12th_Percentage         3
Attendance             62
Projects               28
Programming_Skill      30
Communication_Skill    30
Aptitude_Score         45
Package_LPA            31
Application_Date       82
dtype: int64

Duplicate rows:
0

Data types:
Student_ID                        str
Name                              str
Gender                            str
Branch                            str
CGPA                          float64
10th_Percentage               float64
12th_Percentage               float64
Attendance                    float64
Backlogs                        int64
Internship                        str
Projects                      float64
Certifications                  int64
Programming_Skill             float64
Communication_Skill           float64
Aptitude_Score                float64
Placement_Status                  str
Package_LPA                       str
Graduation_Year                 int64
Application_Date       datetime64[us]
dtype: object

In [84]:
df[df['CGPA']>10]

Empty DataFrame
Columns: [Student_ID, Name, Gender, Branch, CGPA, 10th_Percentage, 12th_Percentage, Attendance, Backlogs, Internship, Projects, Certifications, Programming_Skill, Communication_Skill, Aptitude_Score, Placement_Status, Package_LPA, Graduation_Year, Application_Date]
Index: []

In [85]:
df[df['CGPA']<0]

Empty DataFrame
Columns: [Student_ID, Name, Gender, Branch, CGPA, 10th_Percentage, 12th_Percentage, Attendance, Backlogs, Internship, Projects, Certifications, Programming_Skill, Communication_Skill, Aptitude_Score, Placement_Status, Package_LPA, Graduation_Year, Application_Date]
Index: []

In [86]:
df[df['10th_Percentage']>100]

Empty DataFrame
Columns: [Student_ID, Name, Gender, Branch, CGPA, 10th_Percentage, 12th_Percentage, Attendance, Backlogs, Internship, Projects, Certifications, Programming_Skill, Communication_Skill, Aptitude_Score, Placement_Status, Package_LPA, Graduation_Year, Application_Date]
Index: []

In [87]:
df[df['10th_Percentage']<0]

Empty DataFrame
Columns: [Student_ID, Name, Gender, Branch, CGPA, 10th_Percentage, 12th_Percentage, Attendance, Backlogs, Internship, Projects, Certifications, Programming_Skill, Communication_Skill, Aptitude_Score, Placement_Status, Package_LPA, Graduation_Year, Application_Date]
Index: []

In [88]:
df[df['12th_Percentage']>100]

Empty DataFrame
Columns: [Student_ID, Name, Gender, Branch, CGPA, 10th_Percentage, 12th_Percentage, Attendance, Backlogs, Internship, Projects, Certifications, Programming_Skill, Communication_Skill, Aptitude_Score, Placement_Status, Package_LPA, Graduation_Year, Application_Date]
Index: []

In [89]:
df[df['12th_Percentage']<0]

Empty DataFrame
Columns: [Student_ID, Name, Gender, Branch, CGPA, 10th_Percentage, 12th_Percentage, Attendance, Backlogs, Internship, Projects, Certifications, Programming_Skill, Communication_Skill, Aptitude_Score, Placement_Status, Package_LPA, Graduation_Year, Application_Date]
Index: []

In [90]:
df.to_csv('Student_clean_data.csv',index=False)